# Generated by Django 3.0 on 2019-06-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='planning',
            name='id_instructor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='planning',
            name='id_student',
            field=models.IntegerField(),
        ),
    ]
